# Generated by Django 6.1.1 on 2026-09-14 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('grade', models.CharField(default='12', max_length=10, verbose_name='Grade')),
                ('class_id', models.CharField(default='109576', max_length=20, verbose_name='Class ID')),
                ('profile', models.CharField(default='13', max_length=20, verbose_name='Profile')),
                ('school', models.CharField(default='1846', max_length=20, verbose_name='School')),
                ('ativa', models.BooleanField(default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
            },
        ),
        migrations.CreateModel(
            name='TelegramGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=50, verbose_name='Chat ID')),
                ('ativo', models.BooleanField(default=True)),
                ('turma', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram', to='agenda_app.turma')),
            ],
            options={
                'verbose_name': 'Grupo Telegram',
                'verbose_name_plural': 'Grupos Telegram',
            },
        ),
        migrations.CreateModel(
            name='PortalSecure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_portal', models.CharField(max_length=150)),
                ('senha_criptografada', models.TextField()),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('turma', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal_secure', to='agenda_app.turma')),
            ],
        ),
        migrations.CreateModel(
            name='PortalCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_portal', models.CharField(max_length=150, verbose_name='Usuário no portal')),
                ('senha_portal', models.CharField(max_length=255, verbose_name='Senha no portal')),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('turma', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal', to='agenda_app.turma')),
            ],
            options={
                'verbose_name': 'Usuário do Portal',
                'verbose_name_plural': 'Usuários do Portal',
            },
        ),
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('date', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('download_url', models.URLField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('turma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='agenda_app.turma')),
            ],
            options={
                'ordering': ['date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(blank=True, max_length=150)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alunos', to='agenda_app.turma')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
        migrations.CreateModel(
            name='Conclusao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concluida', models.BooleanField(default=False)),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conclusoes', to='agenda_app.agendaitem')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conclusoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'item')},
            },
        ),
    ]
