# Generated by Django 6.1.1 on 2026-09-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_app', '0001_add_portalsecure'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaitem',
            name='author',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='agendaitem',
            name='links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='agendaitem',
            name='time',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='agendaitem',
            name='type',
            field=models.CharField(blank=True, choices=[('task', 'Tarefa'), ('event', 'Evento'), ('assignment', 'Atividade'), ('assessment', 'Avaliação'), ('online_class', 'Aula online')], default='event', max_length=20),
        ),
    ]
